version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: hcsp-{{ checksum "pom.xml" }}
      - run:
          name: Verify whitelist
          command: ./.circleci/verifyWhitelist.sh
      - run:
          name: Install starter
          command: mvn install -DskipTests -PmavenCentral
      - run:
          name: Test app
          command: mvn verify -PmavenCentral
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: hcsp-{{ checksum "pom.xml" }}
workflows:
  version: 2
  default:
    jobs:
      - test
